=== MicheleMacagno/Assignment1/dtd/nffgInfo.dtd
<!ELEMENT nffgs (nffg+)>

<!ELEMENT nffg (node,node,node*,link+,policy*)>
	<!ATTLIST nffg
		 name  ID 		#REQUIRED
		 update_time	CDATA #REQUIRED
	>
<!ELEMENT node EMPTY>
<!ATTLIST node
	name 			ID 		#REQUIRED
	functional_type		(FW|DPI|NAT|SPAM|CACHE|VPN|WEB_SERVER|WEB_CLIENT|MAIL_SERVER|MAIL_CLIENT)	#REQUIRED	
	
>

<!ELEMENT link EMPTY>
<!ATTLIST link
	name			ID		#REQUIRED
	src					IDREF	#REQUIRED
	dst					IDREF	#REQUIRED
>	

<!ELEMENT policy (traversal?,verification?)>
<!ATTLIST policy
		name 		ID							#REQUIRED
		src			IDREF						#REQUIRED
		dst			IDREF						#REQUIRED
		positivity	(true|false)				#REQUIRED

>

<!ELEMENT verification EMPTY>
<!ATTLIST verification
	
		satisfied			(true|false)				#REQUIRED
		message				CDATA						#REQUIRED
		verification_time	CDATA						#REQUIRED
>

<!ELEMENT traversal  (functionality+)>




<!ELEMENT functionality EMPTY>
<!ATTLIST functionality
		name	(FW|DPI|NAT|SPAM|CACHE|VPN|WEB_SERVER|WEB_CLIENT|MAIL_SERVER|MAIL_CLIENT)	#REQUIRED
>

=== MicheleMacagno/Assignment1/dtd/nffgInfo.xml
<?xml version="1.0"?>
<!DOCTYPE nffgs SYSTEM "nffgInfo.dtd">
<nffgs>
	<nffg name="nffg1" lastUpdate="2015-07-21T21:00:00.000+02:00">
		<node name="node11" functionality="FW"  />
		<node name="node12" functionality="DPI"  />
		<node name="node13" functionality="SPAM"  />

		<link 
			name="link12" 
			src="node11" 
			dst="node12" 
		/>
		
		
		<policy 
			name="policy11" 
			positivity="true"
			src="node11" 
			dst="node12">
			<verification 
						verificationTime="2015-07-21T21:00:00.000+02:00"
						result="true" 
						message="no messages for this policy"
			/>
			
		</policy>
	
		<policy 
			name="policy12" 
			positivity="true"
			src="node11"
			dst="node12"
		>
			<traversal>
				<functionality name="FW" />
				<functionality name="NAT" />
			</traversal>
				
			<verification
				verificationTime="2015-07-21T22:00:00.000+02:00"
				result="true"
				message="no messages for this policy"
			/>
		</policy>


	</nffg>
	
	<nffg 
		name="nffg2" 
		lastUpdate="2015-07-21T21:00:00.000+02:00">
		<node 
			name="node11B" 
			functionality="FW"  />
		<node 
			name="node12B" 
			functionality="DPI"  />
		<node 
			name="node13B" 
			functionality="SPAM"  />

		<link 
			name="link12B" 
			src="node11B" 
			dst="node12B" 
		/>
		
		
		<policy 
			name="policy11B" 
			positivity="true"
			src="node11B" 
			dst="node12B">
			<verification 
					result="false" 
					message="Failed verification"
					verificationTime="2015-07-21T22:00:00.000+02:00"
			/>
			
		</policy>
	
		<policy 
			name="policy12B" 
			positivity="true"
			src="node11B"
			dst="node12B"
		>
			<traversal>
				<functionality name="DPI" />
			</traversal>
			
		</policy>
	</nffg>
</nffgs>
