=== MicheleMacagno/Assignment1/xsd/nffgInfo.xsd
<?xml version="1.0"?>
<xsd:schema 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/nffgInfo" 
	xmlns:tns="http://www.example.org/nffgInfo" 

	elementFormDefault="qualified">
	
	<xsd:element name="nffgs">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="nffg" type="tns:Nffg" maxOccurs="unbounded">

					<xsd:key name="node_name">
						<xsd:selector xpath="tns:node" />
						<xsd:field xpath="tns:name" />
					</xsd:key>


					<!-- enforce uniqueness of link names inside a nffg -->
					<xsd:key name="link_name">
						<xsd:selector xpath="tns:link" />
						<xsd:field xpath="tns:name" />
					</xsd:key>


					<!-- node references for links -->
					<xsd:keyref name="ref_link_src_node" refer="tns:node_name">
						<xsd:selector xpath="tns:link" />
						<xsd:field xpath="tns:src" />
					</xsd:keyref>

					<xsd:keyref name="ref_link_dst_node" refer="tns:node_name">
						<xsd:selector xpath="tns:link" />
						<xsd:field xpath="tns:dst" />
					</xsd:keyref>
					

					<!-- enforce the src of the policy to be linked to a node name of the 
						nffg -->
					<xsd:keyref name="ref_policy_src_node" refer="tns:node_name">
						<xsd:selector xpath="tns:policy" />
						<xsd:field xpath="tns:src" />
					</xsd:keyref>

					<!-- enforce the dst of the policy to be linked to a node name of the 
						nffg -->
					<xsd:keyref name="ref_policy_dst_node" refer="tns:node_name">
						<xsd:selector xpath="tns:policy" />
						<xsd:field xpath="tns:dst" />
					</xsd:keyref>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>

		<!-- Uniqueness of nffg name -->
		<xsd:key name="nffg_name">
			<xsd:selector xpath="tns:nffg" />
			<xsd:field xpath="tns:name" />
		</xsd:key>
		
		<!-- uniqueness of name of the policy -->
		<xsd:key name="unique_policy">
			<xsd:selector xpath="tns:nffg/tns:policy"></xsd:selector>
			<xsd:field xpath="tns:name" />
		</xsd:key>

	</xsd:element>




	<!-- nffg element declaration -->
	<xsd:complexType name="Nffg">

		<xsd:sequence>
			<xsd:element name="name" type="tns:NameType" />
			<xsd:element name="lastUpdate" type="xsd:dateTime" />
			<xsd:element name="node" minOccurs="2" maxOccurs="unbounded" type="tns:Node" />
			<xsd:element name="link" minOccurs="1" maxOccurs="unbounded" type="tns:Link" />
			<xsd:element name="policy" minOccurs="0" maxOccurs="unbounded" type="tns:Policy" />
		</xsd:sequence>


	</xsd:complexType>

	<!-- Node declaration -->
	<xsd:complexType name="Node">
		<xsd:sequence>
			<xsd:element name="name" type="tns:NameType" />
			<xsd:element name="functionality" type="tns:Functionality" />
		</xsd:sequence>

	</xsd:complexType>

	<!-- Functionalities declaration -->
	<xsd:simpleType name="Functionality">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="FW" />
			<xsd:enumeration value="DPI" />
			<xsd:enumeration value="NAT" />
			<xsd:enumeration value="SPAM" />
			<xsd:enumeration value="CACHE" />
			<xsd:enumeration value="VPN" />
			<xsd:enumeration value="WEB_SERVER" />
			<xsd:enumeration value="WEB_CLIENT" />
			<xsd:enumeration value="MAIL_SERVER" />
			<xsd:enumeration value="MAIL_CLIENT" />
		</xsd:restriction>
	</xsd:simpleType>

	<!-- Node declaration -->
	<xsd:complexType name="Link">
		<xsd:sequence>
			<xsd:element name="name" type="tns:NameType" />
			<xsd:element name="src" type="tns:NameType" />
			<xsd:element name="dst" type="tns:NameType" />
		</xsd:sequence>
	</xsd:complexType>

	<!-- policy declaration -->
	<xsd:complexType name="Policy">
		<xsd:sequence>
			<xsd:element name="name" type="tns:NameType" />

			<!--imposed the result not mandatory, can be computed, right? -->
			<xsd:element name="positivity" type="xsd:boolean" />
			<xsd:element name="src" type="tns:NameType" />
			<xsd:element name="dst" type="tns:NameType" />
			<xsd:element minOccurs="0" maxOccurs="1" name="traversal" type="tns:Traversal" />

			<!-- The element of the verification, include the result of verification, 
				the date/time and a message with further information -->

			<xsd:element name="verification" type="tns:Verification"
				minOccurs="0" maxOccurs="1" />

		</xsd:sequence>
	</xsd:complexType>



	<!-- Traversal policy type definition as extension of reachability property -->
	<xsd:complexType name="Traversal">
				<xsd:sequence>
					<xsd:element name="functionality" type="tns:Functionality"
						minOccurs="1" maxOccurs="unbounded" />
				</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="Verification">
		<xsd:sequence>
			<xsd:element name="verificationTime" type="xsd:dateTime" />
			<xsd:element name="result" type="xsd:boolean" />
			<xsd:element name="message" type="xsd:string" />
		</xsd:sequence>
	</xsd:complexType>


	<!-- name - the name of the NF-FG to get (a string made of alphanumeric 
		characters only, where the first character is alphabetic). -->
	<xsd:simpleType name="NameType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[a-zA-Z][a-zA-Z0-9]*" />
		</xsd:restriction>
	</xsd:simpleType>
	

</xsd:schema>

=== MicheleMacagno/Assignment1/xsd/nffgInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:nffgs 
	xmlns:tns="http://www.example.org/nffgInfo" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.example.org/nffgInfo nffgInfo.xsd ">


	<tns:nffg>
		<tns:name>nffg1</tns:name>
		<tns:lastUpdate>2015-07-21T21:00:00.000+02:00</tns:lastUpdate>

		<tns:node>
			<tns:name>nodo1</tns:name>
			<tns:functionality>FW</tns:functionality>
		</tns:node>

		<tns:node>
			<tns:name>nodo2</tns:name>
			<tns:functionality>NAT</tns:functionality>
		</tns:node>

		<tns:node>
			<tns:name>nodo3</tns:name>
			<tns:functionality>DPI</tns:functionality>
		</tns:node>

		<tns:node>
			<tns:name>nodo4</tns:name>
			<tns:functionality>DPI</tns:functionality>
		</tns:node>

		<tns:node>
			<tns:name>nodo5</tns:name>
			<tns:functionality>DPI</tns:functionality>
		</tns:node>

		<tns:link>
			<tns:name>link1</tns:name>
			<tns:src>nodo1</tns:src>
			<tns:dst>nodo4</tns:dst>
		</tns:link>

		<tns:link>
			<tns:name>link2</tns:name>
			<tns:src>nodo1</tns:src>
			<tns:dst>nodo2</tns:dst>
		</tns:link>

		<tns:policy>
			<tns:name>policy1</tns:name>
			<tns:positivity>true</tns:positivity>
			<tns:src>nodo4</tns:src>
			<tns:dst>nodo1</tns:dst>
			<tns:verification>
				<tns:verificationTime>2016-07-21T21:00:00.000+02:00</tns:verificationTime>
				<tns:result>true</tns:result>
				<tns:message>This policy is Verified</tns:message>
			</tns:verification>
		</tns:policy>
		
		<tns:policy>
			<tns:name>policy2</tns:name>
			<tns:positivity>true</tns:positivity>
			<tns:src>nodo1</tns:src>
			<tns:dst>nodo3</tns:dst>
			<tns:traversal>
				<tns:functionality>DPI</tns:functionality>
			</tns:traversal>
		</tns:policy>

	</tns:nffg>

	<tns:nffg>
		<tns:name>nffg2</tns:name>
		<tns:lastUpdate>2015-07-21T21:00:00.000+02:00</tns:lastUpdate>

		<tns:node>
			<tns:name>nodo1</tns:name>
			<tns:functionality>FW</tns:functionality>
		</tns:node>

		<tns:node>
			<tns:name>nodo2</tns:name>
			<tns:functionality>NAT</tns:functionality>
		</tns:node>

		<tns:node>
			<tns:name>nodo3</tns:name>
			<tns:functionality>DPI</tns:functionality>
		</tns:node>

		<tns:node>
			<tns:name>nodo4</tns:name>
			<tns:functionality>DPI</tns:functionality>
		</tns:node>

		<tns:node>
			<tns:name>nodo5</tns:name>
			<tns:functionality>DPI</tns:functionality>
		</tns:node>

		<tns:link>
			<tns:name>link1</tns:name>
			<tns:src>nodo1</tns:src>
			<tns:dst>nodo4</tns:dst>
		</tns:link>

		<tns:link>
			<tns:name>link2</tns:name>
			<tns:src>nodo1</tns:src>
			<tns:dst>nodo2</tns:dst>
		</tns:link>

		<tns:policy>
			<tns:name>policy3</tns:name>
			<tns:positivity>true</tns:positivity>
			<tns:src>nodo4</tns:src>
			<tns:dst>nodo1</tns:dst>
			<tns:verification>
				<tns:verificationTime>2016-07-21T21:00:00.000+02:00</tns:verificationTime>
				<tns:result>true</tns:result>
				<tns:message>This policy is Verified</tns:message>
			</tns:verification>
		</tns:policy>
		
		<tns:policy>
			<tns:name>policy4</tns:name>
			<tns:positivity>true</tns:positivity>
			<tns:src>nodo1</tns:src>
			<tns:dst>nodo3</tns:dst>
			<tns:traversal>
				<tns:functionality>DPI</tns:functionality>
			</tns:traversal>
		</tns:policy>

	</tns:nffg>
</tns:nffgs>
